In [10]:
import os
import requests
import re
import numpy as np
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (18,14)

In [11]:
# URL of the remote Excel file
remote_file_url = "https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fassets.publishing.service.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F1147095%2FET_3.1_MAR_23.xlsx&wdOrigin=BROWSELINK"

# Path to the local directory to save the file
save_directory = "C:\\Users\\Pranav Prasanth\\Desktop\\data science project\\Petroineos data profiling"

# Path to the existing Excel file (change it according to your file's location)
existing_file_path = "C:\\Users\\Pranav Prasanth\\Desktop\\data science project\\Petroineos data profiling\\ET_3.1_MAR_23.xlsx"

# Check if the existing file exists
if os.path.exists(existing_file_path):
    # Get the last modified timestamp of the existing file
    existing_file_timestamp = os.path.getmtime(existing_file_path)
else:
    # Set the last modified timestamp to 0 if the existing file doesn't exist
    existing_file_timestamp = 0

# Send a HEAD request to get the last modified timestamp of the remote file
response = requests.head(remote_file_url)
remote_file_timestamp = response.headers.get("Last-Modified")

# Check if the remote file is newer than the existing file
if remote_file_timestamp and (not existing_file_timestamp or remote_file_timestamp > existing_file_timestamp):
    # Download the new Excel file
    response = requests.get(remote_file_url)
    new_file_path = os.path.join(save_directory, "data.xlsx")
    with open(new_file_path, "wb") as f:
        f.write(response.content)
    
    # Update the existing file path
    existing_file_path = new_file_path
    print("New dataset downloaded.")

In [27]:
# Opening excell sheet and Dropping empty rows 
df = pd.read_excel(existing_file_path, sheet_name= 'Quarter', header=None)
df_1 = df.drop([0,1,2,3])
df_1.head()

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
4,Column1,1999 \n1st quarter,1999 \n2nd quarter,1999 \n3rd quarter,1999 \n4th quarter,2000 \n1st quarter,2000 \n2nd quarter,2000 \n3rd quarter,2000 \n4th quarter,2001 \n1st quarter,...,2020 \n3rd quarter,2020 \n4th quarter,2021 \n1st quarter,2021 \n2nd quarter,2021\n3rd quarter,2021 \n4th quarter,2022\n1st quarter,2022 2nd quarter,2022 3nd quarter,2022 4th quarter [provisional]
5,Indigenous production [note 2],34382.56,33060.35,34314.67,35341.42,34217.37,30802.13,30427.07,30798.43,29196.34,...,11092.15,12003.22,11698.39,8883.41,10269.05,10311.62,10440.54,9692.65,8635.9,9325.26
6,Crude oil,32030.9,31037.14,32261.61,32932.35,31815.8,28759.57,28539.06,28768.06,27027.79,...,10288.63,11001.75,10831.66,8367.86,9531.72,9507.28,9618.28,8898.84,7878.45,8539.35
7,NGLs [note 3],2351.66,2023.21,2053.06,2409.07,2401.57,2042.56,1888.01,2030.37,2168.55,...,735.05,888.35,781.19,440.47,668.89,734.65,743.35,711.27,670.85,691.81
8,Feedstocks,0,0,0,0,0,0,0,0,0,...,68.46,113.12,85.53,75.08,68.45,69.69,78.91,82.54,86.6,94.1

In [28]:
#making row 4 (year) as columns
df_1.columns = df_1.iloc[0]
df_1

4,Column1,1999 \n1st quarter,1999 \n2nd quarter,1999 \n3rd quarter,1999 \n4th quarter,2000 \n1st quarter,2000 \n2nd quarter,2000 \n3rd quarter,2000 \n4th quarter,2001 \n1st quarter,...,2020 \n3rd quarter,2020 \n4th quarter,2021 \n1st quarter,2021 \n2nd quarter,2021\n3rd quarter,2021 \n4th quarter,2022\n1st quarter,2022 2nd quarter,2022 3nd quarter,2022 4th quarter [provisional]
4,Column1,1999 \n1st quarter,1999 \n2nd quarter,1999 \n3rd quarter,1999 \n4th quarter,2000 \n1st quarter,2000 \n2nd quarter,2000 \n3rd quarter,2000 \n4th quarter,2001 \n1st quarter,...,2020 \n3rd quarter,2020 \n4th quarter,2021 \n1st quarter,2021 \n2nd quarter,2021\n3rd quarter,2021 \n4th quarter,2022\n1st quarter,2022 2nd quarter,2022 3nd quarter,2022 4th quarter [provisional]
5,Indigenous production [note 2],34382.56,33060.35,34314.67,35341.42,34217.37,30802.13,30427.07,30798.43,29196.34,...,11092.15,12003.22,11698.39,8883.41,10269.05,10311.62,10440.54,9692.65,8635.9,9325.26
6,Crude oil,32030.9,31037.14,32261.61,32932.35,31815.8,28759.57,28539.06,28768.06,27027.79,...,10288.63,11001.75,10831.66,8367.86,9531.72,9507.28,9618.28,8898.84,7878.45,8539.35
7,NGLs [note 3],2351.66,2023.21,2053.06,2409.07,2401.57,2042.56,1888.01,2030.37,2168.55,...,735.05,888.35,781.19,440.47,668.89,734.65,743.35,711.27,670.85,691.81
8,Feedstocks,0,0,0,0,0,0,0,0,0,...,68.46,113.12,85.53,75.08,68.45,69.69,78.91,82.54,86.6,94.1
9,Imports [note 4],10086.68,10889.88,11828.64,12063.8,13161.13,13623.23,14267.78,13334.15,12485.16,...,9821.8,10226.07,7322.32,10822.61,11289.28,12297.17,11870.44,11197.28,11952.01,11473.04
10,Crude oil & NGLs,8937.42,9397.88,10350.26,10635.45,11813.79,11981.42,12900.9,12171.58,11638.03,...,9072.45,9366.94,6589.99,9804.33,10364.03,11302.46,10832.16,10344.7,11296.25,10607.82
11,Feedstocks,1149.26,1492.01,1478.38,1428.35,1347.34,1641.81,1366.89,1162.57,847.14,...,749.35,859.13,732.34,1018.29,925.24,994.71,1038.28,852.58,655.76,865.22
12,Exports [note 4],20743.41,21341.24,24225.48,25486.88,24609.94,23894.54,22303.95,22108.75,20832.07,...,9645.11,9640.17,9244.6,7549.21,8458.86,9228.82,8627.96,7354.98,6643.99,8301.84
13,Crude Oil & NGLs,19890.75,20758.26,23590.02,24682.97,23952.26,23224.01,21607.51,21297.59,20110.32,...,9408.09,9444.67,8938.88,7007.27,8095.42,8643.65,8147.79,6945.2,6205.05,7305.85
14,Feedstocks,852.66,582.97,635.45,803.92,657.68,670.53,696.45,811.16,721.75,...,237.02,195.5,305.72,541.94,363.44,585.18,480.17,409.78,438.93,995.99
15,Stock change [note 5],238.41,460.68,-427.93,-468.72,5.83,850.66,-264.86,506.39,-628.05,...,608.22,25.76,136.73,-142.91,312.58,-158.78,8.68,417.29,-627.44,617.09
16,Transfers [note 6],-369.87,-472.96,-207.64,-167.53,-76.22,48.68,-26.36,163.49,655.33,...,-233.35,-304.92,-106.97,288.73,-129.43,194.62,107.86,24.38,106.32,470.08
17,Total supply,23594.36,22596.71,21282.27,21282.08,22698.17,21430.16,22099.67,22693.7,20876.72,...,11643.71,12309.96,9805.87,12302.62,13282.62,13415.8,13799.55,13976.61,13422.81,13583.64
18,Statistical difference [note 7],843.9,495.41,-269.16,-923.72,391,-167.68,186.46,204.67,199.8,...,1.87,3.23,-3.07,-0.65,7.4,6.63,-28.01,-12.51,-1.14,20.63
19,Total demand,22750.47,22101.3,21551.43,22205.8,22307.17,21597.85,21913.21,22489.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
20,Transformation,22666.66,22020.28,21474.62,22124.44,22225.17,21522.85,21845.21,22420.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
21,Petroleum refineries,22666.66,22020.28,21474.62,22124.44,22225.17,21522.85,21845.21,22420.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
22,Energy industry use,83.81,81.02,76.81,81.36,82,75,68,69,0,...,0,0,0,0,0,0,0,0,0,0
23,Oil & gas extraction,83.81,81.02,76.81,81.36,82,75,68,69,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
# Convert the index to timestamps
df_1.index = pd.to_datetime(df_1.index)

# Convert the timezone of the index
df_1.index = df_1.index.tz_convert('UTC')  # Replace 'UTC' with the desired timezone

df_1

4,Column1,1999 \n1st quarter,1999 \n2nd quarter,1999 \n3rd quarter,1999 \n4th quarter,2000 \n1st quarter,2000 \n2nd quarter,2000 \n3rd quarter,2000 \n4th quarter,2001 \n1st quarter,...,2020 \n3rd quarter,2020 \n4th quarter,2021 \n1st quarter,2021 \n2nd quarter,2021\n3rd quarter,2021 \n4th quarter,2022\n1st quarter,2022 2nd quarter,2022 3nd quarter,2022 4th quarter [provisional]
1970-01-01 00:00:00.000000004+00:00,Column1,1999 \n1st quarter,1999 \n2nd quarter,1999 \n3rd quarter,1999 \n4th quarter,2000 \n1st quarter,2000 \n2nd quarter,2000 \n3rd quarter,2000 \n4th quarter,2001 \n1st quarter,...,2020 \n3rd quarter,2020 \n4th quarter,2021 \n1st quarter,2021 \n2nd quarter,2021\n3rd quarter,2021 \n4th quarter,2022\n1st quarter,2022 2nd quarter,2022 3nd quarter,2022 4th quarter [provisional]
1970-01-01 00:00:00.000000005+00:00,Indigenous production [note 2],34382.56,33060.35,34314.67,35341.42,34217.37,30802.13,30427.07,30798.43,29196.34,...,11092.15,12003.22,11698.39,8883.41,10269.05,10311.62,10440.54,9692.65,8635.9,9325.26
1970-01-01 00:00:00.000000006+00:00,Crude oil,32030.9,31037.14,32261.61,32932.35,31815.8,28759.57,28539.06,28768.06,27027.79,...,10288.63,11001.75,10831.66,8367.86,9531.72,9507.28,9618.28,8898.84,7878.45,8539.35
1970-01-01 00:00:00.000000007+00:00,NGLs [note 3],2351.66,2023.21,2053.06,2409.07,2401.57,2042.56,1888.01,2030.37,2168.55,...,735.05,888.35,781.19,440.47,668.89,734.65,743.35,711.27,670.85,691.81
1970-01-01 00:00:00.000000008+00:00,Feedstocks,0,0,0,0,0,0,0,0,0,...,68.46,113.12,85.53,75.08,68.45,69.69,78.91,82.54,86.6,94.1
1970-01-01 00:00:00.000000009+00:00,Imports [note 4],10086.68,10889.88,11828.64,12063.8,13161.13,13623.23,14267.78,13334.15,12485.16,...,9821.8,10226.07,7322.32,10822.61,11289.28,12297.17,11870.44,11197.28,11952.01,11473.04
1970-01-01 00:00:00.000000010+00:00,Crude oil & NGLs,8937.42,9397.88,10350.26,10635.45,11813.79,11981.42,12900.9,12171.58,11638.03,...,9072.45,9366.94,6589.99,9804.33,10364.03,11302.46,10832.16,10344.7,11296.25,10607.82
1970-01-01 00:00:00.000000011+00:00,Feedstocks,1149.26,1492.01,1478.38,1428.35,1347.34,1641.81,1366.89,1162.57,847.14,...,749.35,859.13,732.34,1018.29,925.24,994.71,1038.28,852.58,655.76,865.22
1970-01-01 00:00:00.000000012+00:00,Exports [note 4],20743.41,21341.24,24225.48,25486.88,24609.94,23894.54,22303.95,22108.75,20832.07,...,9645.11,9640.17,9244.6,7549.21,8458.86,9228.82,8627.96,7354.98,6643.99,8301.84
1970-01-01 00:00:00.000000013+00:00,Crude Oil & NGLs,19890.75,20758.26,23590.02,24682.97,23952.26,23224.01,21607.51,21297.59,20110.32,...,9408.09,9444.67,8938.88,7007.27,8095.42,8643.65,8147.79,6945.2,6205.05,7305.85
1970-01-01 00:00:00.000000014+00:00,Feedstocks,852.66,582.97,635.45,803.92,657.68,670.53,696.45,811.16,721.75,...,237.02,195.5,305.72,541.94,363.44,585.18,480.17,409.78,438.93,995.99
1970-01-01 00:00:00.000000015+00:00,Stock change [note 5],238.41,460.68,-427.93,-468.72,5.83,850.66,-264.86,506.39,-628.05,...,608.22,25.76,136.73,-142.91,312.58,-158.78,8.68,417.29,-627.44,617.09
1970-01-01 00:00:00.000000016+00:00,Transfers [note 6],-369.87,-472.96,-207.64,-167.53,-76.22,48.68,-26.36,163.49,655.33,...,-233.35,-304.92,-106.97,288.73,-129.43,194.62,107.86,24.38,106.32,470.08
1970-01-01 00:00:00.000000017+00:00,Total supply,23594.36,22596.71,21282.27,21282.08,22698.17,21430.16,22099.67,22693.7,20876.72,...,11643.71,12309.96,9805.87,12302.62,13282.62,13415.8,13799.55,13976.61,13422.81,13583.64
1970-01-01 00:00:00.000000018+00:00,Statistical difference [note 7],843.9,495.41,-269.16,-923.72,391,-167.68,186.46,204.67,199.8,...,1.87,3.23,-3.07,-0.65,7.4,6.63,-28.01,-12.51,-1.14,20.63
1970-01-01 00:00:00.000000019+00:00,Total demand,22750.47,22101.3,21551.43,22205.8,22307.17,21597.85,21913.21,22489.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
1970-01-01 00:00:00.000000020+00:00,Transformation,22666.66,22020.28,21474.62,22124.44,22225.17,21522.85,21845.21,22420.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
1970-01-01 00:00:00.000000021+00:00,Petroleum refineries,22666.66,22020.28,21474.62,22124.44,22225.17,21522.85,21845.21,22420.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
1970-01-01 00:00:00.000000022+00:00,Energy industry use,83.81,81.02,76.81,81.36,82,75,68,69,0,...,0,0,0,0,0,0,0,0,0,0
1970-01-01 00:00:00.000000023+00:00,Oil & gas extraction,83.81,81.02,76.81,81.36,82,75,68,69,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
#checking NULL data and their sum
df.isnull().sum()

0     0
1     4
2     4
3     4
4     4
     ..
91    4
92    4
93    4
94    4
95    4
Length: 96, dtype: int64

In [40]:
#dropping unwanted datas or null datas
df_1 = df.drop([0,1,2,3])
df_1.head()

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
4,Column1,1999 \n1st quarter,1999 \n2nd quarter,1999 \n3rd quarter,1999 \n4th quarter,2000 \n1st quarter,2000 \n2nd quarter,2000 \n3rd quarter,2000 \n4th quarter,2001 \n1st quarter,...,2020 \n3rd quarter,2020 \n4th quarter,2021 \n1st quarter,2021 \n2nd quarter,2021\n3rd quarter,2021 \n4th quarter,2022\n1st quarter,2022 2nd quarter,2022 3nd quarter,2022 4th quarter [provisional]
5,Indigenous production [note 2],34382.56,33060.35,34314.67,35341.42,34217.37,30802.13,30427.07,30798.43,29196.34,...,11092.15,12003.22,11698.39,8883.41,10269.05,10311.62,10440.54,9692.65,8635.9,9325.26
6,Crude oil,32030.9,31037.14,32261.61,32932.35,31815.8,28759.57,28539.06,28768.06,27027.79,...,10288.63,11001.75,10831.66,8367.86,9531.72,9507.28,9618.28,8898.84,7878.45,8539.35
7,NGLs [note 3],2351.66,2023.21,2053.06,2409.07,2401.57,2042.56,1888.01,2030.37,2168.55,...,735.05,888.35,781.19,440.47,668.89,734.65,743.35,711.27,670.85,691.81
8,Feedstocks,0,0,0,0,0,0,0,0,0,...,68.46,113.12,85.53,75.08,68.45,69.69,78.91,82.54,86.6,94.1

In [41]:
# Converting the first row as string
df_1.iloc[0].astype(str).replace('\n','')

0                            Column1
1                 1999 \n1st quarter
2                 1999 \n2nd quarter
3                 1999 \n3rd quarter
4                 1999 \n4th quarter
                   ...
92                2021 \n4th quarter
93                 2022\n1st quarter
94                  2022 2nd quarter
95                  2022 3nd quarter
96    2022 4th quarter [provisional]
Name: 4, Length: 97, dtype: object

In [42]:
#making row 4 as header
df_1.columns = df_1.iloc[0]
df_1

4,Column1,1999 \n1st quarter,1999 \n2nd quarter,1999 \n3rd quarter,1999 \n4th quarter,2000 \n1st quarter,2000 \n2nd quarter,2000 \n3rd quarter,2000 \n4th quarter,2001 \n1st quarter,...,2020 \n3rd quarter,2020 \n4th quarter,2021 \n1st quarter,2021 \n2nd quarter,2021\n3rd quarter,2021 \n4th quarter,2022\n1st quarter,2022 2nd quarter,2022 3nd quarter,2022 4th quarter [provisional]
4,Column1,1999 \n1st quarter,1999 \n2nd quarter,1999 \n3rd quarter,1999 \n4th quarter,2000 \n1st quarter,2000 \n2nd quarter,2000 \n3rd quarter,2000 \n4th quarter,2001 \n1st quarter,...,2020 \n3rd quarter,2020 \n4th quarter,2021 \n1st quarter,2021 \n2nd quarter,2021\n3rd quarter,2021 \n4th quarter,2022\n1st quarter,2022 2nd quarter,2022 3nd quarter,2022 4th quarter [provisional]
5,Indigenous production [note 2],34382.56,33060.35,34314.67,35341.42,34217.37,30802.13,30427.07,30798.43,29196.34,...,11092.15,12003.22,11698.39,8883.41,10269.05,10311.62,10440.54,9692.65,8635.9,9325.26
6,Crude oil,32030.9,31037.14,32261.61,32932.35,31815.8,28759.57,28539.06,28768.06,27027.79,...,10288.63,11001.75,10831.66,8367.86,9531.72,9507.28,9618.28,8898.84,7878.45,8539.35
7,NGLs [note 3],2351.66,2023.21,2053.06,2409.07,2401.57,2042.56,1888.01,2030.37,2168.55,...,735.05,888.35,781.19,440.47,668.89,734.65,743.35,711.27,670.85,691.81
8,Feedstocks,0,0,0,0,0,0,0,0,0,...,68.46,113.12,85.53,75.08,68.45,69.69,78.91,82.54,86.6,94.1
9,Imports [note 4],10086.68,10889.88,11828.64,12063.8,13161.13,13623.23,14267.78,13334.15,12485.16,...,9821.8,10226.07,7322.32,10822.61,11289.28,12297.17,11870.44,11197.28,11952.01,11473.04
10,Crude oil & NGLs,8937.42,9397.88,10350.26,10635.45,11813.79,11981.42,12900.9,12171.58,11638.03,...,9072.45,9366.94,6589.99,9804.33,10364.03,11302.46,10832.16,10344.7,11296.25,10607.82
11,Feedstocks,1149.26,1492.01,1478.38,1428.35,1347.34,1641.81,1366.89,1162.57,847.14,...,749.35,859.13,732.34,1018.29,925.24,994.71,1038.28,852.58,655.76,865.22
12,Exports [note 4],20743.41,21341.24,24225.48,25486.88,24609.94,23894.54,22303.95,22108.75,20832.07,...,9645.11,9640.17,9244.6,7549.21,8458.86,9228.82,8627.96,7354.98,6643.99,8301.84
13,Crude Oil & NGLs,19890.75,20758.26,23590.02,24682.97,23952.26,23224.01,21607.51,21297.59,20110.32,...,9408.09,9444.67,8938.88,7007.27,8095.42,8643.65,8147.79,6945.2,6205.05,7305.85
14,Feedstocks,852.66,582.97,635.45,803.92,657.68,670.53,696.45,811.16,721.75,...,237.02,195.5,305.72,541.94,363.44,585.18,480.17,409.78,438.93,995.99
15,Stock change [note 5],238.41,460.68,-427.93,-468.72,5.83,850.66,-264.86,506.39,-628.05,...,608.22,25.76,136.73,-142.91,312.58,-158.78,8.68,417.29,-627.44,617.09
16,Transfers [note 6],-369.87,-472.96,-207.64,-167.53,-76.22,48.68,-26.36,163.49,655.33,...,-233.35,-304.92,-106.97,288.73,-129.43,194.62,107.86,24.38,106.32,470.08
17,Total supply,23594.36,22596.71,21282.27,21282.08,22698.17,21430.16,22099.67,22693.7,20876.72,...,11643.71,12309.96,9805.87,12302.62,13282.62,13415.8,13799.55,13976.61,13422.81,13583.64
18,Statistical difference [note 7],843.9,495.41,-269.16,-923.72,391,-167.68,186.46,204.67,199.8,...,1.87,3.23,-3.07,-0.65,7.4,6.63,-28.01,-12.51,-1.14,20.63
19,Total demand,22750.47,22101.3,21551.43,22205.8,22307.17,21597.85,21913.21,22489.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
20,Transformation,22666.66,22020.28,21474.62,22124.44,22225.17,21522.85,21845.21,22420.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
21,Petroleum refineries,22666.66,22020.28,21474.62,22124.44,22225.17,21522.85,21845.21,22420.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
22,Energy industry use,83.81,81.02,76.81,81.36,82,75,68,69,0,...,0,0,0,0,0,0,0,0,0,0
23,Oil & gas extraction,83.81,81.02,76.81,81.36,82,75,68,69,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
df_2 = df_1.drop([4])
df_2

4,Column1,1999 \n1st quarter,1999 \n2nd quarter,1999 \n3rd quarter,1999 \n4th quarter,2000 \n1st quarter,2000 \n2nd quarter,2000 \n3rd quarter,2000 \n4th quarter,2001 \n1st quarter,...,2020 \n3rd quarter,2020 \n4th quarter,2021 \n1st quarter,2021 \n2nd quarter,2021\n3rd quarter,2021 \n4th quarter,2022\n1st quarter,2022 2nd quarter,2022 3nd quarter,2022 4th quarter [provisional]
5,Indigenous production [note 2],34382.56,33060.35,34314.67,35341.42,34217.37,30802.13,30427.07,30798.43,29196.34,...,11092.15,12003.22,11698.39,8883.41,10269.05,10311.62,10440.54,9692.65,8635.9,9325.26
6,Crude oil,32030.9,31037.14,32261.61,32932.35,31815.8,28759.57,28539.06,28768.06,27027.79,...,10288.63,11001.75,10831.66,8367.86,9531.72,9507.28,9618.28,8898.84,7878.45,8539.35
7,NGLs [note 3],2351.66,2023.21,2053.06,2409.07,2401.57,2042.56,1888.01,2030.37,2168.55,...,735.05,888.35,781.19,440.47,668.89,734.65,743.35,711.27,670.85,691.81
8,Feedstocks,0,0,0,0,0,0,0,0,0,...,68.46,113.12,85.53,75.08,68.45,69.69,78.91,82.54,86.6,94.1
9,Imports [note 4],10086.68,10889.88,11828.64,12063.8,13161.13,13623.23,14267.78,13334.15,12485.16,...,9821.8,10226.07,7322.32,10822.61,11289.28,12297.17,11870.44,11197.28,11952.01,11473.04
10,Crude oil & NGLs,8937.42,9397.88,10350.26,10635.45,11813.79,11981.42,12900.9,12171.58,11638.03,...,9072.45,9366.94,6589.99,9804.33,10364.03,11302.46,10832.16,10344.7,11296.25,10607.82
11,Feedstocks,1149.26,1492.01,1478.38,1428.35,1347.34,1641.81,1366.89,1162.57,847.14,...,749.35,859.13,732.34,1018.29,925.24,994.71,1038.28,852.58,655.76,865.22
12,Exports [note 4],20743.41,21341.24,24225.48,25486.88,24609.94,23894.54,22303.95,22108.75,20832.07,...,9645.11,9640.17,9244.6,7549.21,8458.86,9228.82,8627.96,7354.98,6643.99,8301.84
13,Crude Oil & NGLs,19890.75,20758.26,23590.02,24682.97,23952.26,23224.01,21607.51,21297.59,20110.32,...,9408.09,9444.67,8938.88,7007.27,8095.42,8643.65,8147.79,6945.2,6205.05,7305.85
14,Feedstocks,852.66,582.97,635.45,803.92,657.68,670.53,696.45,811.16,721.75,...,237.02,195.5,305.72,541.94,363.44,585.18,480.17,409.78,438.93,995.99
15,Stock change [note 5],238.41,460.68,-427.93,-468.72,5.83,850.66,-264.86,506.39,-628.05,...,608.22,25.76,136.73,-142.91,312.58,-158.78,8.68,417.29,-627.44,617.09
16,Transfers [note 6],-369.87,-472.96,-207.64,-167.53,-76.22,48.68,-26.36,163.49,655.33,...,-233.35,-304.92,-106.97,288.73,-129.43,194.62,107.86,24.38,106.32,470.08
17,Total supply,23594.36,22596.71,21282.27,21282.08,22698.17,21430.16,22099.67,22693.7,20876.72,...,11643.71,12309.96,9805.87,12302.62,13282.62,13415.8,13799.55,13976.61,13422.81,13583.64
18,Statistical difference [note 7],843.9,495.41,-269.16,-923.72,391,-167.68,186.46,204.67,199.8,...,1.87,3.23,-3.07,-0.65,7.4,6.63,-28.01,-12.51,-1.14,20.63
19,Total demand,22750.47,22101.3,21551.43,22205.8,22307.17,21597.85,21913.21,22489.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
20,Transformation,22666.66,22020.28,21474.62,22124.44,22225.17,21522.85,21845.21,22420.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
21,Petroleum refineries,22666.66,22020.28,21474.62,22124.44,22225.17,21522.85,21845.21,22420.03,20676.92,...,11641.84,12306.73,9808.94,12303.27,13275.23,13409.17,13827.56,13989.12,13423.95,13563.01
22,Energy industry use,83.81,81.02,76.81,81.36,82,75,68,69,0,...,0,0,0,0,0,0,0,0,0,0
23,Oil & gas extraction,83.81,81.02,76.81,81.36,82,75,68,69,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
#counting the number of rows
len(df_3.index)

19

In [11]:
#counting the number of columns
df_3.count()

4
1999 \n1st quarter                19
1999 \n2nd quarter                19
1999 \n3rd quarter                19
1999 \n4th quarter                19
2000 \n1st quarter                19
                                  ..
2021\n3rd quarter                 19
2021 \n4th quarter                19
2022\n1st quarter                 19
2022 2nd quarter                  19
2022 3nd quarter [provisional]    19
Length: 95, dtype: int64

In [12]:
# finding the minimum value of 2022 3nd quarter [provisional]
df_3['2022 3nd quarter [provisional]'].min(axis = 0)

-629.24

In [13]:
# finding the maximum value of various entries over time
df_3.max(axis=1)

Column1
Indigenous production [note 2]     35341.42
Crude oil                          32932.35
NGLs [note 3]                       2409.07
Feedstocks                           126.92
Imports [note 4]                   17235.98
Crude oil & NGLs                   15936.11
Feedstocks                          2314.08
Exports [note 4]                   25486.88
Crude Oil & NGLs                   24682.97
Feedstocks                          1205.63
Stock change [note 5]                970.49
Transfers [note 6]                   655.33
Total supply                       23594.36
Statistical difference [note 7]      843.90
Total demand                       23184.06
Transformation                     23184.06
Petroleum refineries               23184.06
Energy industry use                   83.81
Oil & gas extraction                  83.81
dtype: float64

In [14]:
# finding the mean or average value of various entries over time
df_3.mean(axis=1)

Column1
Indigenous production [note 2]     17689.340737
Crude oil                          16370.870421
NGLs [note 3]                       1279.174000
Feedstocks                            39.296105
Imports [note 4]                   13440.773579
Crude oil & NGLs                   11972.692105
Feedstocks                          1468.082105
Exports [note 4]                   12740.534842
Crude Oil & NGLs                   12178.033789
Feedstocks                           562.502000
Stock change [note 5]                 19.965789
Transfers [note 6]                  -382.569474
Total supply                       18026.974842
Statistical difference [note 7]        2.152105
Total demand                       18024.822842
Transformation                     18018.328105
Petroleum refineries               18018.328105
Energy industry use                    6.494737
Oil & gas extraction                   6.494737
dtype: float64

In [45]:
# finding the median value of 2022 2nd quarter
df_3['2022 2nd quarter'].median(axis = 0)

NameError: name 'df_3' is not defined

In [46]:
# checking for missing colums
df.isnull()

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
0,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [47]:
X = list(df_3.iloc[14])
Y = list(df_3.iloc[12])
plt.bar(X, Y, color='brown')
plt.title("Demand v/s Supply")
plt.xlabel("Total demand")
plt.ylabel("Total supplies")
plt.show()

NameError: name 'df_3' is not defined